# Generated by Django 2.2.1 on 2019-07-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('paragraph', models.CharField(max_length=2000)),
                ('image_url', models.URLField()),
                ('date', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('link_url', models.URLField()),
            ],
        ),
    ]
